
name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Is tag push: ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "GITHUB_TOKEN exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          node --version
          npm --version

      - name: Publish Linux (AppImage and deb)
        run: npm run publish:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

  publish-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Is tag push: ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "GITHUB_TOKEN exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          node --version
          npm --version

      - name: Publish Windows
        run: npm run publish:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

  publish-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "Tag name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Is tag push: ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "GITHUB_TOKEN exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          node --version
          npm --version

      - name: Publish macOS
        run: npm run publish:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder

  cleanup-release:
    runs-on: ubuntu-latest
    needs: [publish-linux, publish-windows, publish-macos]
    if: always() && (needs.publish-linux.result == 'success' || needs.publish-windows.result == 'success' || needs.publish-macos.result == 'success')
    steps:
      - name: Clean unwanted files from release
        run: |
          set -e  # 启用错误时退出
          
          echo "🧹 Starting release cleanup for tag: ${{ github.ref_name }}"
          
          # 检查 GitHub CLI 是否可用
          if ! command -v gh &> /dev/null; then
            echo "❌ GitHub CLI not found"
            exit 1
          fi
          
          # 验证环境变量
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ GH_TOKEN not set"
            exit 1
          fi
          
          # 测试 GitHub API 连接
          echo "🔗 Testing GitHub API connection..."
          if ! gh api user > /dev/null 2>&1; then
            echo "❌ Cannot connect to GitHub API"
            exit 1
          fi
          echo "✅ GitHub API connection successful"
          
          # 等待确保所有上传完成
          echo "⏰ Waiting 20 seconds for uploads to complete..."
          sleep 20
          
          echo "📡 Attempting to get release for tag: ${{ github.ref_name }}"
          
          # 获取 release ID，添加详细错误信息
          RELEASE_RESPONSE=$(gh api repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} 2>&1) || {
            echo "❌ Failed to get release information:"
            echo "$RELEASE_RESPONSE"
            echo "🔍 Checking if release exists..."
            gh api repos/${{ github.repository }}/releases --jq '.[] | select(.tag_name == "${{ github.ref_name }}") | {id, tag_name, name}' || true
            exit 1
          }
          
          RELEASE_ID=$(echo "$RELEASE_RESPONSE" | jq -r '.id' 2>/dev/null)
          
          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "null" ]; then
            echo "❌ Could not extract release ID from response"
            echo "📄 Response: $RELEASE_RESPONSE"
            exit 1
          fi
          
          echo "✅ Found release ID: $RELEASE_ID"
          
          # 列出所有 assets
          echo "📁 Getting current release assets..."
          ASSETS_RESPONSE=$(gh api repos/${{ github.repository }}/releases/$RELEASE_ID/assets 2>&1) || {
            echo "❌ Failed to get assets:"
            echo "$ASSETS_RESPONSE"
            exit 1
          }
          
          echo "📁 Current release assets:"
          echo "$ASSETS_RESPONSE" | jq -r '.[] | "- \(.name) (ID: \(.id))"' || {
            echo "❌ Failed to parse assets response"
            echo "📄 Raw response: $ASSETS_RESPONSE"
            exit 1
          }
          
          # 查找并删除不需要的文件
          echo "🔍 Looking for unwanted assets..."
          UNWANTED_ASSETS=$(echo "$ASSETS_RESPONSE" | jq -r '.[] | select(.name | test("\\.(yml|yaml|blockmap)$")) | .id' 2>/dev/null)
          
          if [ -n "$UNWANTED_ASSETS" ] && [ "$UNWANTED_ASSETS" != "" ]; then
            echo "🎯 Found unwanted assets to delete:"
            echo "$ASSETS_RESPONSE" | jq -r '.[] | select(.name | test("\\.(yml|yaml|blockmap)$")) | "- \(.name) (ID: \(.id))"'
            
            echo "$UNWANTED_ASSETS" | while read -r asset_id; do
              if [ -n "$asset_id" ] && [ "$asset_id" != "null" ]; then
                ASSET_NAME=$(echo "$ASSETS_RESPONSE" | jq -r ".[] | select(.id == $asset_id) | .name" 2>/dev/null)
                echo "🗑️  Deleting: $ASSET_NAME (ID: $asset_id)"
                
                if gh api --method DELETE repos/${{ github.repository }}/releases/assets/$asset_id 2>/dev/null; then
                  echo "✅ Successfully deleted: $ASSET_NAME"
                else
                  echo "❌ Failed to delete: $ASSET_NAME"
                fi
              fi
            done
          else
            echo "🎉 No unwanted files found!"
          fi
          
          echo "🏁 Cleanup completed successfully!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
