name: Build and Release

on:
  push:
    tags:
      - 'v*' # 只有推送标签如 v1.0.0 时才会触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set up Electron builder cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}

      - name: Build Electron app
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            npm run build:linux
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            npm run build:win
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npm run build:mac
          fi

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.exe
            dist/*.portable.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
